services:
  backend-p_mat:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASS: ADM%698#
    volumes:
      - ./data:/app/data

  frontend-p_mat:
    build: ./frontend
    ports:
      - "9000:80"
    restart: always

